baseURL = "https://amplify-ios-workshop.go-aws.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amplify iOS Workshop"
theme = "hugo-theme-learn"
uglyurls = true
googleAnalytics = "UA-151590472-1"
sectionPagesMenu = "main"

# this is not necessary anymore with hugo 0.60 https://gohugo.io/news/0.60.0-relnotes/
#pygmentsCodeFences = true
#[blackfriday]
#hrefTargetBlank = true

[markup.highlight]
codeFences = true

[markup.goldmark.renderer]
unsafe= true
# https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "SÃ©bastien Stormacq"
description = "Amplify iOS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle = true
disableInlineCopyToClipBoard = true

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @sebsto"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=sebsto"
weight = 1

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]
